dist: xenial
language: python
env:
    - TOXENV=py35
    - TOXENV=py37
    - TOXENV=cov
matrix:
    allow_failures:
        - env: TOXENV=cov
install:
    - pip install tox
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet;
      coveralls;
      fi
